In [81]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [82]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [83]:
#preprocess the data
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [84]:
# Encode categorical variables
label_encoder_gender =LabelEncoder()
data['Gender'] =label_encoder_gender.fit_transform(data['Gender'])

In [85]:
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [86]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [87]:
## Divide the dataset into indepent and dependent features
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

##Split the data in training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

##Scale the features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [88]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

#### ANN regression problem statement

In [89]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [90]:
##Build oue Ann model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),## HL1 connected with input layer
    Dense(32,activation='relu'), ##HL2
    Dense(1) ##output layer

])
## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_12 (Dense)            (None, 64)                832

 dense_13 (Dense)            (None, 32)                2080

 dense_14 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [91]:
## set up the tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

#setup Tensorboard
log_dir="regressionlogs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [92]:
#set up Early stopping 
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [93]:
#Train the model
history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[early_stopping_callback,tensorflow_callback]
    )

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 100371.7734 - mae: 100371.7734 - val_loss: 98493.7578 - val_mae: 98493.7578
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 99552.8672 - mae: 99552.8672 - val_loss: 96848.3594 - val_mae: 96848.3594
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 96703.5703 - mae: 96703.5703 - val_loss: 92672.5469 - val_mae: 92672.5469
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 91122.0781 - mae: 91122.0781 - val_loss: 85752.2734 - val_mae: 85752.2734
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 83074.9766 - mae: 83074.9766 - val_loss: 76987.7344 - val_mae: 76987.7344
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 73783.3047 - mae: 73783.3047 - val_loss: 68004.4609 - val_mae: 68004.4609
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 64924.2852 - mae: 64924.2852 - val_loss: 60385.1211 - val_mae: 60385.1211
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 58080.7539 - mae: 58080.7539 - val_loss: 55139.8672 - val_mae: 55139.8672
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 53768.3789 - mae: 53768.3789 - val_loss: 52306.6406 - val_mae: 52306.6406
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 51603.7305 - mae: 51603.7305 - val_loss: 51148.9219 - val_mae: 51148.9219
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 50726.9922 - mae: 50726.9922 - val_loss: 50792.9492 - val_mae: 50792.9492
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 50416.7461 - mae: 50416.7461 - val_loss: 50687.3867 - val_mae: 50687.3867
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 50279.2383 - mae: 50279.2383 - val_loss: 50625.4141 - val_mae: 50625.4141
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 50202.6094 - mae: 50202.6094 - val_loss: 50577.2617 - val_mae: 50577.2617
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 50146.8281 - mae: 50146.8281 - val_loss: 50545.6172 - val_mae: 50545.6172
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 50096.7422 - mae: 50096.7422 - val_loss: 50506.1758 - val_mae: 50506.1758
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 50051.6719 - mae: 50051.6719 - val_loss: 50486.1133 - val_mae: 50486.1133
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 50014.0352 - mae: 50014.0352 - val_loss: 50450.8906 - val_mae: 50450.8906
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 49978.4727 - mae: 49978.4727 - val_loss: 50427.6562 - val_mae: 50427.6562
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 49945.9805 - mae: 49945.9805 - val_loss: 50407.4805 - val_mae: 50407.4805
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 49917.0781 - mae: 49917.0781 - val_loss: 50390.9492 - val_mae: 50390.9492
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 49888.3477 - mae: 49888.3477 - val_loss: 50367.8320 - val_mae: 50367.8320
Epoch 23/100
250/250 [==============================] - 1s 2ms/step - loss: 49865.3242 - mae: 49865.3242 - val_loss: 50351.2109 - val_mae: 50351.2109
Epoch 24/100
250/250 [==============================] - 1s 2ms/step - loss: 49839.2812 - mae: 49839.2812 - val_loss: 50343.7461 - val_mae: 50343.7461
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 49819.6328 - mae: 49819.6328 - val_loss: 50331.0781 - val_mae: 50331.0781
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 49795.9375 - mae: 49795.9375 - val_loss: 50327.8516 - val_mae: 50327.8516
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 49777.4102 - mae: 49777.4102 - val_loss: 50312.5742 - val_mae: 50312.5742
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 49758.2891 - mae: 49758.2891 - val_loss: 50303.9297 - val_mae: 50303.9297
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49740.8477 - mae: 49740.8477 - val_loss: 50299.9531 - val_mae: 50299.9531
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 49726.2031 - mae: 49726.2031 - val_loss: 50296.8281 - val_mae: 50296.8281
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 49711.4375 - mae: 49711.4375 - val_loss: 50298.1992 - val_mae: 50298.1992
Epoch 32/100
250/250 [==============================] - 1s 2ms/step - loss: 49696.1484 - mae: 49696.1484 - val_loss: 50291.5586 - val_mae: 50291.5586
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49676.1758 - mae: 49676.1758 - val_loss: 50290.5977 - val_mae: 50290.5977
Epoch 34/100
250/250 [==============================] - 0s 2ms/step - loss: 49662.6445 - mae: 49662.6445 - val_loss: 50273.7383 - val_mae: 50273.7383
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 49650.6172 - mae: 49650.6172 - val_loss: 50270.2695 - val_mae: 50270.2695
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 49638.8242 - mae: 49638.8242 - val_loss: 50279.9375 - val_mae: 50279.9375
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 49623.3672 - mae: 49623.3672 - val_loss: 50276.7891 - val_mae: 50276.7891
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 49615.2891 - mae: 49615.2891 - val_loss: 50278.1406 - val_mae: 50278.1406
Epoch 39/100
250/250 [==============================] - 0s 2ms/step - loss: 49602.2930 - mae: 49602.2930 - val_loss: 50282.6367 - val_mae: 50282.6367
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 49590.8594 - mae: 49590.8594 - val_loss: 50264.4141 - val_mae: 50264.4141
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 49580.8398 - mae: 49580.8398 - val_loss: 50266.7461 - val_mae: 50266.7461
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 49571.1250 - mae: 49571.1250 - val_loss: 50259.5234 - val_mae: 50259.5234
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 49562.7461 - mae: 49562.7461 - val_loss: 50268.1953 - val_mae: 50268.1953
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 49552.2539 - mae: 49552.2539 - val_loss: 50253.3008 - val_mae: 50253.3008
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49546.3594 - mae: 49546.3594 - val_loss: 50259.2695 - val_mae: 50259.2695
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 49538.2305 - mae: 49538.2305 - val_loss: 50264.0625 - val_mae: 50264.0625
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 49529.0312 - mae: 49529.0312 - val_loss: 50259.2969 - val_mae: 50259.2969
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49520.3555 - mae: 49520.3555 - val_loss: 50259.9375 - val_mae: 50259.9375
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49513.7773 - mae: 49513.7773 - val_loss: 50256.4961 - val_mae: 50256.4961
Epoch 50/100
250/250 [==============================] - 0s 2ms/step - loss: 49506.5117 - mae: 49506.5117 - val_loss: 50252.4805 - val_mae: 50252.4805
Epoch 51/100
250/250 [==============================] - 1s 2ms/step - loss: 49497.8359 - mae: 49497.8359 - val_loss: 50251.1367 - val_mae: 50251.1367
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 49492.6211 - mae: 49492.6211 - val_loss: 50251.5586 - val_mae: 50251.5586
Epoch 53/100
250/250 [==============================] - 1s 5ms/step - loss: 49483.7734 - mae: 49483.7734 - val_loss: 50254.1680 - val_mae: 50254.1680
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49479.0430 - mae: 49479.0430 - val_loss: 50252.6406 - val_mae: 50252.6406
Epoch 55/100
250/250 [==============================] - 1s 4ms/step - loss: 49473.5664 - mae: 49473.5664 - val_loss: 50262.9531 - val_mae: 50262.9531
Epoch 56/100
250/250 [==============================] - 1s 5ms/step - loss: 49468.7773 - mae: 49468.7773 - val_loss: 50249.3008 - val_mae: 50249.3008
Epoch 57/100
250/250 [==============================] - 1s 4ms/step - loss: 49460.8047 - mae: 49460.8047 - val_loss: 50250.1758 - val_mae: 50250.1758
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 49452.4375 - mae: 49452.4375 - val_loss: 50239.7812 - val_mae: 50239.7812
Epoch 59/100
250/250 [==============================] - 1s 4ms/step - loss: 49446.3164 - mae: 49446.3164 - val_loss: 50254.9961 - val_mae: 50254.9961
Epoch 60/100
250/250 [==============================] - 1s 4ms/step - loss: 49443.4844 - mae: 49443.4844 - val_loss: 50254.2422 - val_mae: 50254.2422
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 49435.5039 - mae: 49435.5039 - val_loss: 50247.6875 - val_mae: 50247.6875
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 49431.1406 - mae: 49431.1406 - val_loss: 50251.1367 - val_mae: 50251.1367
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 49424.3203 - mae: 49424.3203 - val_loss: 50256.8945 - val_mae: 50256.8945
Epoch 64/100
250/250 [==============================] - 0s 2ms/step - loss: 49421.6133 - mae: 49421.6133 - val_loss: 50253.8477 - val_mae: 50253.8477
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 49414.9102 - mae: 49414.9102 - val_loss: 50246.2852 - val_mae: 50246.2852
Epoch 66/100
250/250 [==============================] - 0s 2ms/step - loss: 49408.2812 - mae: 49408.2812 - val_loss: 50244.4883 - val_mae: 50244.4883
Epoch 67/100
250/250 [==============================] - 1s 2ms/step - loss: 49405.4297 - mae: 49405.4297 - val_loss: 50243.8047 - val_mae: 50243.8047
Epoch 68/100
250/250 [==============================] - 0s 2ms/step - loss: 49398.7188 - mae: 49398.7188 - val_loss: 50258.5977 - val_mae: 50258.5977

In [94]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [95]:
%tensorboard --logdir regressionlogs/fit20260523-175643

Reusing TensorBoard on port 6007 (pid 6632), started 1:04:05 ago. (Use '!kill 6632' to kill it.)

In [96]:
## Evaluate moodel on test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 4ms/step - loss: 50239.7812 - mae: 50239.7812
Test MAE : 50239.78125

In [97]:
model.save('regression_model.h5')

c:\Users\kotad\ANN end to end project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(